version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    timezone: Etc/UTC
  open-pull-requests-limit: 10
  reviewers:
  - nathan-at-least
  assignees:
  - nathan-at-least
  labels:
  - "A-CI"
