name: Build and Test
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install apt dependencies
        run: >
          sudo apt-get install build-essential pkg-config libc6-dev m4
          g++-multilib autoconf libtool ncurses-dev unzip git python3
          python3-zmq zlib1g-dev curl bsdmainutils automake libtinfo5

      - uses: actions/checkout@v2

      - run: ./zcutil/fetch-params.sh

      - name: Toolchain Versions
        run: >
          make --version &&
          as --version

      - run: make -C ./depends DEBUG=1

      - run: ./autogen.sh

      - run: >
          CONFIG_SITE="$PWD/depends/x86_64-pc-linux-gnu/share/config.site"
            ./configure ||
          find '/home/runner/work/zcashd-barebones/zcashd-barebones/depends/x86_64-pc-linux-gnu/vendored-sources/'
            -exec ls -ld '{}' \; &&
          false

      - run: make

      - run: ./qa/zcash/full_test_suite.py
